version: '3.4'

networks:
  default:
    external:
      name: examples-ddd-clean-architecture_default

# portはあえてずらします。サンプルコードでよくそのまま使われちゃうので
services:
  mysql:
    platform: linux/x86_64
    image: mysql:8
    volumes:
      - "./external/docker/images/mysql/init:/docker-entrypoint-initdb.d"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "33306:3306"

