version: '3.4'

# portはあえてずらします。サンプルコードでよくそのまま使われちゃうので
services:
  mysql:
    platform: linux/x86_64
    image: mysql:8
    volumes:
      - "./external/docker/images/mysql/init:/docker-entrypoint-initdb.d"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "33306:3306"
  # これ外してただのshell実行でいいかも
  flyway:
    image: flyway/flyway:8.5.13-alpine
    volumes:
      - "./external/migration/conf:/flyway/conf"
      - "./external/migration/sql:/flyway/sql"

